### ISSUE TITLE
Request to run promotion for Dlive

### ISSUE THREAD

**Issue by engrbrain1** [dreamvids/dlive#2]
I am a true follower of dlive I would like to contribute also to dlive in a way which i hope will be be fitting to you.
I have a facebook page which I believe can be used to promote dlive with the use of a promotional ad will I will provide.
I want to request your permission before I can carry out the promotion or task. In doing this, I hope to contribute to the dlive community in my own way.

**Comment by quadrifoglio** [comment]
lol

**Comment by p-cauty** [comment]
Hey! This isn't the dlive repo, this is an old dead project with the same name, sorry bro ;)
